name: Deploy to GitFocused Page

# Run workflow whenever there is a push to the master branch
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-gitfocused-page:
    # use ubuntu-latest to execute steps
      runs-on: ubuntu-latest
      steps:
        # use GitHub's checkout action to chekout code from master branch
        - uses: actions/checkout@v2
        
        # setup .NET SDK 5.0.101
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.101
        
        # publish Blazor project to release folder
        - name: Publish .NET Core Project
          run: dotnet publish GitHubWebsite.csproj -c Release -o release --nologo
          
        

        # changes the base-tag in index.html from '/' to 'GitFocused' to match GitHub Pages repository subdirectory    
        - name: Change base-tag in index.html from / to GitFocused
          run: sed 's/<base href="\/" \/>/<base href="\/GitFocused\/" \/>/g' release/wwwroot/index.html
          
        # copy index.html to 404.html to serve the same file when a file is not found
        - name: copy index.html to 404.html
          run: cp release/wwwroot/index.html release/wwwroot/404.html
        # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
        - name: Add .nojekyll file
          run: touch release/wwwroot/.nojekyll
        - name: Commit wwwroot to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@3.7.1
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: fh-pages
            FOLDER: release/wwwroot
        
        # change base tag in index.html from '/' to 'GitFocused' to match repository subdirectory
        - name: Change base tag in index.html
          run: sed -i 
